
language: python

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7

python:
  - "3.6"

services:
  - docker

install: 
  - pip3 install -r requirements.txt

before_script: 
  - pip3 install docker-compose

script: 
  - docker-compose run app sh -c "python3 manage.py test && flake8" 